FROM node:20-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./
ENV NODE_ENV=production
RUN npm install --build-from-source

COPY . .

CMD ["node", "six_degrees_worker.js"]
